name: DeSmuME

on:
  - push
  - pull_request

jobs:
  build:
    name: Build DeSmuME (Linux)
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2

      - name: install dependencies
        run: sudo apt update && sudo apt install meson libsdl2-dev libpcap-dev libgtk-3-dev

      - name: meson
        run: |
          cd desmume/src/frontend/posix/
          meson build

      - name: ninja
        run: ninja -C desmume/src/frontend/posix/build

  build_macos:
    name: Build DeSmuME (macOS)
    runs-on: macOS-11

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.2
      
      - name: xcodebuild
        run: |
          cd desmume/src/frontend/cocoa/
          xcodebuild archive -project "DeSmuME (Latest).xcodeproj" -scheme "DeSmuME (macOS App; Intel64 -- Latest Xcode)" -arch x86_64 -archivePath "$(pwd)/desmume.xcarchive" | xcpretty -c
      
      - name: make zip
        run: |
          cd desmume/src/frontend/cocoa/desmume.xcarchive/Products/Applications/
          7z a DeSmuME.app.zip DeSmuME.app

      - name: Upload artifict
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macos
          path: desmume/src/frontend/cocoa/desmume.xcarchive/Products/Applications/DeSmuME.app.zip
          if-no-files-found: error 
